# Generated by bootstrap.sh
# OCI Configuration for GitOps Metal3 OCI

tenancy_ocid     = "ocid1.tenancy.oc1..aaaaaaaantb3j7xzwqx5wwdpu3pq6ja7r6rdjnr2dwlqsqbnwkmzu3io6vmq"
compartment_ocid = "ocid1.compartment.oc1..aaaaaaaawhet65vhvsgulz5hpshqwd7uhxdr4ngrr7k3u3wjs6wya2ukfqnq"
user_ocid        = "ocid1.user.oc1..aaaaaaaav2ss6r5yfr2eqwagahwav6hizyb6xb6htlyb7t4mvoo2a74lgxtq"
region           = "us-ashburn-1"

# GitHub for OIDC (informational - auth via API key)
github_owner = "vietcgi"
github_repo  = "gitops-metal3-oci"

# SSH public key for VM access
ssh_public_key = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC5/lrhHAQdTRfppzfA7Emn/hcSHobEpl6LzNFsxD9Pi0+sRT8K2shdwZ02vk+eZT3chi6Pwf5Cb82/NS7yLlq4eUxG/IKp1HxVKTdTQgA3E0HF/mmwveCnuR55iUvNNliRyWbBnY/uw5yfhVrDIyAwP+rE16M/ROlorbskJ4R6fFMr4M4o2PjAFL2KH+1lnMrtbNoovqg7/xLBhiDGhs6sNHl4E34PHICkH7Xqkh+7TCDbpjDGxMuNL5RG1zMG1fLFfJX0QIQanN2jHJU2NEMBVWB+BxNYWKWACHQevubER8KdxksBj3Newi65zx2enDoKNE6kpzi2lqPdDpUXwwVf kevin-on-kevin"

# Project name
project_name = "metal3-oci"
