apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: baremetal-operator-system

resources:
  - namespace.yaml
  # Metal3 CRDs (from https://github.com/metal3-io/baremetal-operator)
  - crds/metal3.io_bmceventsubscriptions.yaml
  - crds/metal3.io_dataimages.yaml
  - crds/metal3.io_firmwareschemas.yaml
  - crds/metal3.io_hardwaredata.yaml
  - crds/metal3.io_hostfirmwarecomponents.yaml
  - crds/metal3.io_hostfirmwaresettings.yaml
  - crds/metal3.io_preprovisioningimages.yaml
  # Metal3 components
  - ironic-configmap.yaml
  - ironic-deployment.yaml
  - baremetal-operator.yaml
