---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vuabaohiem-admin-auth
  namespace: vuabaohiem
spec:
  encryptedData:
    ADMIN_PASSWORD: AgBex2S07UJ0FIbmA/z9jAglf/j6KPGeJO7lrwDsM9RrO73blcDsb9uZ29O3+cdDM8Nlft3I+D3Yb650GXsuE3fBSDoreuRd1rIXpFBqggxJuRrrh2o4XB14vNNXajjZqdM5vZCHFnHwbojzBz7+c8wt16VXvZiYroHdkWfC4SIa4+WSzve5ZHtzuhg26n1dwPN79PlRkD/iYljDP61ASiWzDIfGxIQVySToM162dXHA+E+xHQi0AOJFamIdFvYsKCbmbYbrkC3Akn1nSlOq+xrRZTAFxomkeTTZEJhFGXXfJFKk4e1ihiqlb+ekuYgKNpuWoJOM5oMCSWhEImNS5b3Dlok5jtamcf35dG2/mGdBXG7KP0HmGE03aI2e4Jp/xr8fB7o+UnILDsThcUU5cSuCjRdOgqgIU8wsLJclH95CuwUk1EP2NVv4pRjVOUDJZzceziiGT3L7ep/ZMyZ8FYrts8HbVJkkiztj/7+9sNPdMleH2TbbUEhuSs7IagQCoameDdylBtbsfONEg+zBOC6LrTnM0OLJDvy0zMXFRrOZli7e2zSpPvX2SCqmXTq33WBHq4075SV59aalVu7FkzMFkBW/wvrKHOcVodi8gZ79COQh7lC1+ihtq1WwxH0eNYiotBSUTCnnp2urpIJJOAm4ZEuFkTBxceIDEz7MYj0bEfPlg+N4E7ACGfujvGrgamaAmjhY7d0yoqedUUIKq8eG2sY=
    ADMIN_USERNAME: AgB9/sTvScf/BrDC5+JYrXahRCGk6mrws5HTKIto2h0KPlgUE7nu8j0I8w4n1nyR0j2yfAEXFNDKQG9HKBL0TRaypbndZEjH8DQaDCjsODa15nvhXQQdlErzaWR86iY6hGJW9BQZ1YzI729fu7G1NiDaLZ+mF6c74qN5gyYJCDpGEW3yCMoxQz27j/F5P0K3Ufb5ScipNSzJxZeM703XQ4G+oKTGWsAsNetcjPXzE5XrV5StW0J4todbIl+EBTPHaGg2t3O6QJkxXaerdQTQbvGMeOyIvNffgq7Pp1+lAmV1FSqft0v1ovvIX1Gim3OtuuAgIvmV1CicFVtwYegoyixNshiwJhgzv0t3nYQpPoYmfTSLeFoBM/FN2k4sGpQnsMHYdvh5ZqZ2YvWQLTKz8POGckQGYQuKXT9v97MgMRvF8I/08CgHsJtPz5VbdbDjGMXOuo6fxvPQ14aRAcA7cN3AuK/PCLK48W+UntkwAqOUJzZBhbrJrMJOGhWoVcVizl1jGfBlLIeEgia31nONmJ2GnrYsImrVzvZuekREWxIwq6QACfxHFnwL5aNMo7L5tG0wTBynosD3E1+e6f13tW4IguYfWJmetcfrFxCNWHIRbICi7biUOKRJ5YFSXiAFYWrvDJR/S8bOaj5ItJpVcVzexbC+BjLzd8QtgouDCHYHmJRsiqQPMExwcvld1KJs9rP3YsjYjg==
  template:
    metadata:
      name: vuabaohiem-admin-auth
      namespace: vuabaohiem
    type: Opaque
