# Example Hardware Definition
#
# Copy this file and modify for each bare metal machine.
# Tinkerbell uses hardware definitions to know how to provision machines.
#
# Required fields:
#   - id: Unique identifier (usually UUID)
#   - metadata.facility.facility_code: Location identifier
#   - network.interfaces: Network interface configuration
#
# After creating the hardware definition, create a workflow to provision it.
#
---
apiVersion: tinkerbell.org/v1alpha1
kind: Hardware
metadata:
  name: worker-01
  namespace: tink-system
spec:
  # Unique ID - use a UUID or the machine's serial number
  id: "00000000-0000-0000-0000-000000000001"

  metadata:
    # Facility/location information
    facility:
      facility_code: "colo-1"
      plan_slug: "bare-metal"

    # Instance metadata (will be available to cloud-init)
    instance:
      hostname: "worker-01"
      operating_system:
        distro: "ubuntu"
        version: "24.04"
      tags:
        - "k3s-worker"
        - "production"

  # Network configuration
  network:
    interfaces:
      - dhcp:
          # MAC address of the primary NIC
          mac: "00:00:00:00:00:01"  # CHANGE THIS
          hostname: "worker-01"
          lease_time: 86400
          # Static IP (optional)
          ip:
            address: "10.0.2.10"
            netmask: "255.255.255.0"
            gateway: "10.0.2.1"
          # DNS servers
          name_servers:
            - "8.8.8.8"
            - "8.8.4.4"

  # Disk configuration
  disks:
    - device: "/dev/sda"  # Primary disk

  # IPMI/BMC configuration (optional, for power control)
  # Uncomment if your hardware has IPMI
  # bmc:
  #   ip: "192.168.1.100"
  #   username: "admin"
  #   password: "password"
