---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: qualityspace-admin-auth
  namespace: qualityspace
spec:
  encryptedData:
    ADMIN_PASSWORD: AgBdUZx+s5dlT3OfHZ97g5DL6Pkr7WrVAf/jmiJs13+YQOqCZEtiqfNsem3c0T86xJM2ueC+rnAGGYVrRoXapBWbDtOW7zb40ZhkdQ0e7o3+4zNqTfTUOr7e77LAoSbPXvRXgTfyoHfdVcUAeAt1urHVHFYg7RI6wO60oBJRMqOjZG4SPQkAkURMTfIbdRmNq5J/zYMZ3N4r2bXel/WRy7rvaVd/TxaV+hPe9qH55dXVaZIBeR2MD3Y/kuGhfmDTusZ4QPGqyMWIiUqOcIPLePiRGHlcQtFG0KL0Au1sQuoN8ykAuyPrNx//LQiy8rm4q20bPsMP0XbaA26VrTkn0wtx6TGzSwVBfrSHj/xIGf4Cr/wC6rCIqipr28VrgUDKWvl96zbJgOS4uPMXemqQ7O2x7+VAsJtPlnFMXht50RFwFAvKHa/S+IgNmv3LuXJ1ezFJ4jx+uN+/rHDbF/8Qpf+MA4UulJl8+QENM+xRAAU/bnQBNA9q2XgnZIXxxxchej4uotiS4TR/6cGLNPefunqjIG1gWQ3R6qAxQP8g/gz4HINsKo3R0b8yWqAAaRunOYN8+d7F5dwKra9LwW/5NSLrZ1/kb9TglOuYsOxB5LNP+X3PTLjxHPIVbnZAKnlNdWX7bZm4h+teKmMb5RfKsGeoKIqhGi1pq4Rw1G7by8e1mr+swdV0vopYehieFG8+HtFDeFRF630TzzGWu4X8KwxV
    ADMIN_USERNAME: AgA2p95/oqfrgceRoazZ7/fzLT/Oz0cLEmzcXkaFmAGfSXmPJAzaqJzB5i3jjpuTDGQ7DHHd5tnwVTa0BQOI4U35qDSVS0aF7oKfS//t2zt3H9UPKAbHlCsQ00yJFp9dlb/iqilYNTW/pvCyaGaXB2U1yxF1IHtOYSUxqeGJ4QJXFYN5OA/+J6iFpEezt5KBWzoKa7DlmV1mTPGq2/8TELdtUWRzBGgqI+FXyHyq9jGJvrvACjRGdlfOVqZqgF0pbLOHBW1JQZ1a8YUelwLvfTMyejMV+x2Vkd1A+mGjNJQIzKysPdUkzptDDZ6xvhDNAAvW5XWtlIRRIH+t7UKH+skxpDdi5oOXQyxp7M5byjaj6yAGTgOqGM8fkgYD1FzRrbU4mkn0yuNdFPlEdfngddYvjXL2/+TzwrCX3c6F5e1cjgq1+A02YSuRG1ILNSgxWpBa0Hgw+YonS7DM7S28vdyfts3lZqEYiApvfgUOPmXoSeOreU4tZ8/XlHMuvv7q7JfBxcJgw1NtdEV5ZThuzZB83/GjcFsk09aZow1KJUgiGDXhwfz6fj3paoKRxuRZYsUPtdS96aEEreSvHIiVzGmfX5RUJQ13MkcfM2/ITOLHfqa/o2PtXusfUYAedkW6oxXFBfyZ1CK2jMDPllPO6EGbjs7TUeNBr27aRwwGjdcbDNukvMo/bXsomHb6O7J2YAUSzJoWjg==
  template:
    metadata:
      name: qualityspace-admin-auth
      namespace: qualityspace
    type: Opaque
