apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: baohiemxe
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - reference-grant.yaml
  - httproute.yaml
  - secrets-sealed.yaml
  - keepalive-cronjob.yaml
