---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: baohiemxe-secrets
  namespace: baohiemxe
spec:
  encryptedData:
    SMTP_PASS: AgBF1e1C374hisQ+RUF2bJ2v4nsmKux+MaYR9pJhQJGEBcr0B0vf3MMDhqmoui70VPQG9E08EEaYTx8LoQ6iyOkWCtEToUgWWGinDW8pkVZk5Fx2sZBOd7+LeFLSyla6sr/jPdrIJXUhlqbgzTWiyOeJ+e4eqmAP9TMUdKX8THQOnmkd0xpewmnMgEtV7JVZ7Xl8bKmwFtfafk0cHkOX1JCJIrve2tl7rga5yptQD2GQpLP/UkDblB9ir8HTwCqNf3KFyK7aFb8842Tv3l1YM0eIcpb0wA/CPSS5Ym/cRXH7n2g/3znZXxau47egB4HLtOhgUwFNnnevi6iWPm6/yUn5A579BlTJwYHIG0nALJzNT96yXqUUT1o+aqDZMkW1o+Ue5OXUqhk7FcWMw/rZc8+R/zAj9nUbe4/pj+IzJmGrdAJL5BTWjgNXfykndmFD1Xg2OapGEvI+EviuwZ1LRAQsYlBJ+/+gq4xjpfUDF0bOlA/XQy93LWtLaUcELIl1LUjbjirqBWUoaegRjDNEZzzPbmd2QbYBU52Ni17L+BZmtjM+wt9HRyK62YiZP/W1Set39vYddRQYyoVshstC46Yo4si+r+fyTRcRBvLgeW2/8L2ALQvmWuTIA6o/cgZWvtHVdL75jE7mBCtZFaC2o4b6B/4GEU3Z1KbWgKwQ00ZRtUgibr9YV31pngvxx+jL3rkqaHXrOXtB5IXYimAErKEX6uwgXSGiu9KOF2abzQ4Mz1+YhPU=
    TURNSTILE_SECRET_KEY: AgCj0IgB8iGZOucK32o9fe9Jq2e410Okr2bi98N8+o4Ll0fqudhmFmsvoiupLPTnSKhupiNJ3zhO53U5h0+7o25wlu622VeYAlxF8zEvcHP/ucpcrWm8Zo4Uo5iMGjxcKbg9yCFLbd5yPvXrPv7DLID+UxfERoq/QMkgglZnEnL/F6KF2mdJvfrpfhI+VtJeybOKaeGABuoSCNwwCYVwx0or4trLC81DpKyjXdQtxbRmGAMAlJ6bO7599NQz1hoLfgvfX5w478MnERsORJZAXAiNSIsPEpCpMdmOQ50xDEgILmVoLObieB0PbjvGQRbCjmTpbV1prasbwxSdbhQiBRnqv4iA42yUaAQhqdVeLZxPW0O+Ty28i4hjDLW4nqQEH5bFC5V6e8DBZ+ZFEaWeLuwHUqqDHTBl23WvQE8MuyjZ1MwwJW3dvYxQEd59riuNVQ7tlu4NN6gy5e0CpgBpbVcOQtaJ0z9t06sJZty43jpnNrTB7CPUWMeHNmqy0MMPM0d4jD3s6DLidnUpRkqYgJ/4knUCig7I8MymU+jK09mMT9VVt+bN3j4kYOPAwbOJxWaCieO7kKtPIqfA8U25J73YmEWwLvS6TH+7mwbq5NPi68dXfmxDSQ2YZxSdGxuZU+T/91WGyUbZdspB/QrmDuIRalBEDTIrfgHgw8p3E6qM80IXGaa94lknCDrsDt+ChOIoyBCWNLCqNDg3i+Vsm7sN4EQOjFBS59NRuP8nYPW5XdiQ6w==
  template:
    metadata:
      name: baohiemxe-secrets
      namespace: baohiemxe
