---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: baohiemxe-secrets
  namespace: baohiemxe
spec:
  encryptedData:
    TURNSTILE_SECRET_KEY: AgBslCBGyp8RyEhfke/i1HQipLtAzcR4HT9XlO2vGgWYOOmumKw7bCe4Tyxpc9E/nQ73eqUqRTxe6/Z8UJU4pzI4OdHjxjzM6VQXfuSDLtph9Low+DpMaw97yeNaCzaelnlVFgYOl/udGqEMVHl98lRkFV8dSiCgfySKkjoZ3lJnJr2qk7ZAFRQEHzuvBcfMTCMG5xT4sCd75pLCnsYc31RLAJm3eICwYIrgpDZt/cgz1v5ZYAyklJKiyQEaC/ka1Q8nXH6SuCiwGuae02UpGKnltmVsUcmATDiL0Cgg3XQa4TsWgI3rDDyyHrcpXKUz+wwtjgpBUhEkmebAnv+VW6Mau7tNKLv7uunKjaadddom0cs9+/sZus40urrdsbsRQ9EsIzml65A2hVfeEcquRu9cooz8a7r8kz53qnHkyBh+Xhi/9D/Og4AWdK66ub9/+a9o5FTfgtanQS8QgBr6OAT3jjdPcrAq/WUu7zxBzeEDs5xiJf9Mte7BtxW2FBV0s2sGNa3bO1B676klYohhqHlYjLKYxFtUgQEj/XuxnCfIaJnVOCTBoEoslfZ2X+v4xFAaU9BgqsUspzGP0CrLzXdTMfbnE5wu+Lv7kLKMbxCy4c6tF+uS2zVQzr8QX1aMiwYMqNsQXgdWMqH/CTcDVq+6Q1U56tyGwGoXuy8Vj0b4aJP4yty4nnOl0Jyx+okVCHqFbj+aUSyyAGq43110zKJWjEcuxfist8HNDlW+HKaayypNcw==
  template:
    metadata:
      name: baohiemxe-secrets
      namespace: baohiemxe
